# site settings
title: TRANSFORMATION DIGITALE
subtitle: by ACSEO
email: contact@acseo.fr
description: La transformation digitale au service des startups et des grands groupes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1060 Rue René Descartes
city: Aix-En-Provence
state:
zip_code: 13100
country: France
phone: 04 42 38 70 46


paginate: 10
paginate_path: posts/page/:num/

collections:
  step:
    output : true
    permalink: :collection/:title:output_ext
  posts:
    output : true
    permalink: :collection/:title:output_ext

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/acseo
pinterest_url:
slack_url:
twitter_url: https://twitter.com/acseo

# build settings
markdown: kramdown

sass:
  style: compressed


plugins:
    - jekyll-paginate
